name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.0.1

  Test:
    runs-on: macOS-latest

    services: 
      wiremock:
        image: wiremock/wiremock:2.33.2
        options: >-
          -help
        ports: 
          -8080:8080

    steps:
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app && /usr/bin/xcodebuild -version
      # - name: Remove docker deps
      #   run: rm -rf ~/Library/Group\ Containers/group.com.docker && rm -rf ~/Library/Containers/com.docker.docker && rm -rf ~/.docker
      # - uses: docker-practice/actions-setup-docker@master
      # - run: |
      #     set -x
      #     docker version
      #     docker run --rm hello-world

      - name: Go to Vendor directory and start wiremock
        run: cd Template/Vendor && docker run -d --name wiremock-container -p 8080:8080 -v $PWD:/home/wiremock wiremock/wiremock
      - name: Install dependencies
        run: echo `pwd` && echo `ls` && pod install
      - name: Run sourcery to generate secrets file
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        run: Pods/Sourcery/bin/sourcery --templates ./Template/Helpers/ --output ./Template/Helpers/ --sources ./Template/ --args api_secret_key=$API_SECRET_KEY
      - name: Run unit tests
        run: xcodebuild test -scheme Dev\ Template -workspace Template.xcworkspace  -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0' -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}